dist: trusty
sudo: require
language: cpp
compiler:
    - clang
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - cmake
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./test/unit_tests/unit_tests
