dist: trusty
sudo: require
language: cpp
compiler:
    - clang
install:
    - wget http://www.cmake.org/files/v3.14/cmake-3.14.2.tar.gz
    - tar xf cmake-3.14.2.tar.gz
    - cd cmake-3.14.2
    - ./bootstrap --system-curl
    - make
    - sudo make install
    - cd ..
before_script:
    - mkdir build
    - cd build
    - cmake ..
script:
    - cmake --build .
    - ./test/unit_tests/unit_tests
