dist: trusty
sudo: require
language: cpp
compiler:
    - clang
install:
    ############################################################################
    # Install a recent CMake
    ############################################################################
    - |
        if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
            CMAKE_URL="https://cmake.org/files/v3.14/cmake-3.14.2-Linux-x86_64.tar.gz"
            mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
            export PATH=${DEPS_DIR}/cmake/bin:${PATH}
        else
            brew install cmake || brew upgrade cmake
        fi
    - cmake --version
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - clang-6.0
before_script:
    - mkdir build
    - cd build
    - cmake ..
script:
    - cmake --build .
    - ./test/unit_tests/unit_tests
